# Ansible managed
---
version: "3.2"

services:
  ftiaxe:
    image: travissouth/ftiaxe
    build: 
      context: ./
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "10"
        compress: "true"
